FROM sqlwwx/puppeteer

WORKDIR /app/

COPY package.json yarn.lock ./

RUN yarn --frozen-lockfile --no-cache --production && \
  rm -rf /tmp/* && rm -rf $HOME/.npm/_cacache && rm -f package.json package-lock.json

ENV PORT=7001
ENV SCREEN_ALLOW_FILE_SCHEME=true
ENV CHROMIUM_ARGS=--no-sandbox,--disable-gpu,--single-process,--disable-dev-shm-usage
